development:
  adapter: postgresql
  encoding: unicode
  database: catalog_development
  pool: 5
  host: localhost
  username: slate
  password: slate
test:
  adapter: postgresql
  encoding: unicode
  database: catalog_test
  pool: 5
  host: localhost
  username: slate
  password: slate